# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Modern AndroidX & Jetpack support
android.useAndroidX=true

# Code style & packaging
kotlin.code.style=official
android.nonTransitiveRClass=true

# KSP engine configuration
ksp.useKSP2=true
android.disallowKotlinSourceSets=false

# Recommended performance optimization for dependency constraints
android.dependency.excludeLibraryComponentsFromConstraints=true